# Generated by Django 5.2 on 2026-06-06 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='created_data',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='updated_data',
            new_name='updated_date',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='created_data',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='updated_data',
            new_name='updated_date',
        ),
    ]
